### ISSUE TITLE
[Question] Is the `sleep 2` really necessary?

### ISSUE THREAD

**Issue by inooid** [codeship/jet-tutorial#2]
I trimmed down the `check.rb` to only have a postgres database that it has to check, but if I take out the `sleep 2` from my `check.rb` script I cannot seem to connect to the database anymore. Is it really necessary to wait for 2 seconds before running the database check? This seems like an awkward thing to set though or does it function another purpose?

I seem to run into database connection problems in my Ruby on Rails projects too.

My trimmed down `check.rb` file:

```ruby
require 'pg'

def log(message)
  puts "\e[34m#{message}\e[0m"
end

sleep 2 # if I remove this line, the database connection will not be setup

log 'Checking PostgreSQL server...'
pg = PG.connect(
  host: ENV['POSTGRES_HOST'],
  dbname: ENV['POSTGRES_DB'],
  user: ENV['POSTGRES_USER']
)
log pg.exec('SELECT version();').first['version']
```

**Comment by mlocher** [comment]
The sleep itself is required, as containers take a different amount of time to start up and if you run the check too early the database container might not be running yet.

The solution with `sleep` was the most easy at the time, but you could also implement the solution mentioned at http://documentation.codeship.com/private/docker/docker/services-and-databases/#waiting-for-a-service-to-start
