### ISSUE TITLE
Rethinkdb Configuration?

### ISSUE THREAD

**Issue by chriscantu** [codeship/jet-tutorial#3]
Hi, I was curious if you have a configuration for rethinkdb.  I couldn't find an example on codeship.com.  

I tried localhost:28015 but couldn't get it to connect.

**Comment by mlocher** [comment]
Ahoy @chriscantu, why not use the official container available at https://hub.docker.com/_/rethinkdb/?

**Comment by chriscantu** [comment]
Hi @mlocher, 

The intent was to use the codeship built in service but I can pivot.  I will give it a shot.

**Comment by mlocher** [comment]
Are you using the Docker based infrastructure (currently available via an invitation only), which this project is a sample project for, or are you using the default platform? If not, a RethinkDB server is already running on the default port with default credentials.

In any case, this project is not the best place to reach out for support, please contact support@codeship.com and include a link to the project / failing build if possible.

**Comment by chriscantu** [comment]
@mlocher - Yes, I am using Docker based infrastructure.  I will reach out to the support email you listed.  Thank you for responding.  Stay awesome!

![awesome](http://lovelace-media.imgix.net/uploads/18/e31fcb60-7a62-0132-43a0-0ebc4eccb42f.gif?)
