### ISSUE TITLE
jet with docker 1.10.1 don't work

### ISSUE THREAD

**Issue by ireinhart** [codeship/jet-tutorial#6]
jet and docker 1.10.1 won't work together. Container start hang up jet and docker ps.

Please fix.

**Comment by mlocher** [comment]
@bfosberry could you look into this?

**Comment by bfosberry** [comment]
Hey, could you give us an idea of what you are running? Can you paste in your services and steps files as well as any dockerfile?

**Comment by ireinhart** [comment]
At the last hours I try some different thing. I have now an working project and the main project that won't work.

Docker write this to syslog:

`eb 19 13:22:38 innoman docker[28119]: time="2016-02-19T13:22:38.945636982Z" level=warning msg="DEPRECATED: Setting host configuration options when the container starts is deprecated and will be removed in Docker 1.12"
Feb 19 13:22:38 innoman docker[28119]: 2016/02/19 13:22:38 http: panic serving @: runtime error: slice bounds out of range
Feb 19 13:22:38 innoman docker[28119]: goroutine 89 [running]:
Feb 19 13:22:38 innoman docker[28119]: net/http.(*conn).serve.func1(0xc821e522c0, 0x7f2c77b5df30, 0xc820022430)
Feb 19 13:22:38 innoman docker[28119]: /usr/local/go/src/net/http/server.go:1287 +0xb5
Feb 19 13:22:38 innoman docker[28119]: github.com/docker/docker/volume/store.(*VolumeStore).Dereference(0xc8210d1c00, 0x7f2c78b90110, 0xc822807ec0, 0xc8227c1e00, 0x40)
Feb 19 13:22:38 innoman docker[28119]: /usr/src/docker/.gopath/src/github.com/docker/docker/volume/store/store.go:301 +0x62b
Feb 19 13:22:38 innoman docker[28119]: github.com/docker/docker/daemon.(*Daemon).registerMountPoints(0xc820069080, 0xc8227396c0, 0xc820da6000, 0x0, 0x0)
Feb 19 13:22:38 innoman docker[28119]: /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/volumes.go:148 +0xf26
Feb 19 13:22:38 innoman docker[28119]: github.com/docker/docker/daemon.(*Daemon).setHostConfig(0xc820069080, 0xc8227396c0, 0xc820da6000, 0x0, 0x0)
Feb 19 13:22:38 innoman docker[28119]: /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/daemon.go:1356 +0x51
Feb 19 13:22:38 innoman docker[28119]: github.com/docker/docker/daemon.(*Daemon).ContainerStart(0xc820069080, 0xc82112e9b7, 0x40, 0xc820da6000, 0x0, 0x0)
Feb 19 13:22:38 innoman docker[28119]: /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/start.go:38 +0x342
Feb 19 13:22:38 innoman docker[28119]: github.com/docker/docker/api/server/router/container.(*containerRouter).postContainersStart(0xc820be4540, 0x7f2c76aaffd0, 0xc821fe4540, 0x7f2c76aafea0, 0xc820ad14a0, 0xc8200a2000, 0xc821fe4450, 0x0, 0x0)
Feb 19 13:22:38 innoman docker[28119]: /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/container/container_routes.go:182 +0x114
Feb 19 13:22:38 innoman docker[28119]: github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.postContainersStart)-fm(0x7f2c76aaffd0, 0xc821fe4540, 0x7f2c76aafea0, 0xc820ad14a0, 0xc8200a2000, 0xc821fe4450, 0x0, 0x0)
Feb 19 13:22:38 innoman docker[28119]: /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/container/container.go:50 +0x74
Feb 19 13:22:38 innoman docker[28119]: github.com/docker/docker/api/server.versionMiddleware.func1(0x7f2c76aaffd0, 0xc821fe4540, 0x7f2c76aafea0, 0xc820ad14a0, 0xc8200a2000, 0xc821fe4450, 0x0, 0x0)
Feb 19 13:22:38 innoman docker[28119]: /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware.go:155 +0x83a
Feb 19 13:22:38 innoman docker[28119]: github.com/docker/docker/api/server.(*Server).corsMiddleware.func1(0x7f2c78b80a28, 0xc82005f440, 0x7f2c76aafea0, 0xc820ad14a0, 0xc8200a2000, 0xc821fe4450, 0x0, 0x0)
Feb 19 13:22:38 innoman docker[28119]: /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware.go:134 +0xfa
Feb 19 13:22:38 innoman docker[28119]: github.com/docker/docker/api/server.(*Server).userAgentMiddleware.func1(0x7f2c78b80a28, 0xc82005f440, 0x7f2c76aafea0, 0xc820ad14a0, 0xc8200a2000, 0xc821fe4450, 0x0, 0x0)
Feb 19 13:22:38 innoman docker[28119]: /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware.go:117 +0x4be
Feb 19 13:22:38 innoman docker[28119]: github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7f2c76aafea0, 0xc820ad14a0, 0xc8200a2000)
Feb 19 13:22:38 innoman docker[28119]: /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:169 +0x2ad
Feb 19 13:22:38 innoman docker[28119]: net/http.HandlerFunc.ServeHTTP(0xc820f31e80, 0x7f2c76aafea0, 0xc820ad14a0, 0xc8200a2000)
Feb 19 13:22:38 innoman docker[28119]: /usr/local/go/src/net/http/server.go:1422 +0x3a
Feb 19 13:22:38 innoman docker[28119]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc820d87040, 0x7f2c76aafea0, 0xc820ad14a0, 0xc8200a2000)
Feb 19 13:22:38 innoman docker[28119]: /usr/src/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e
Feb 19 13:22:38 innoman docker[28119]: github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc820ae2a90, 0x7f2c76aafea0, 0xc820ad14a0, 0xc8200a2000)
Feb 19 13:22:38 innoman docker[28119]: /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
Feb 19 13:22:38 innoman docker[28119]: net/http.serverHandler.ServeHTTP(0xc82005a840, 0x7f2c76aafea0, 0xc820ad14a0, 0xc8200a2000)
Feb 19 13:22:38 innoman docker[28119]: /usr/local/go/src/net/http/server.go:1862 +0x19e
Feb 19 13:22:38 innoman docker[28119]: net/http.(*conn).serve(0xc821e522c0)
Feb 19 13:22:38 innoman docker[28119]: /usr/local/go/src/net/http/server.go:1361 +0xbee
Feb 19 13:22:38 innoman docker[28119]: created by net/http.(*Server).Serve
Feb 19 13:22:38 innoman docker[28119]: /usr/local/go/src/net/http/server.go:1910 +0x3f6`

I try to get the problem isolated. At the moment I think, it has something do to with `volumes_from`. If I remove my volumes_from, the container is staring and running.

**Comment by bfosberry** [comment]
Hey! Thanks for reporting this, it sounds like something we are doing is triggering a bug in docker. By moving off of that deprecated option it might solve it. We'll work on that as well as supporting the ne compose features, and will test locally to try and replicate.

thanks
Brendan

**Comment by ireinhart** [comment]
So, now I have an example project, that is small. The attached zip file contains all required files.

With docker 1.10.1 (You have to restart the docker daemon to get the error from jet):
`{BuildImageFinished=image_name:"codeship_innomanfiles" service_name:"innomanfiles"}
{StepFinished=step_name:"client unit tests" type:STEP_FINISHED_TYPE_ERROR}
Post http://unix.sock/v1.18/containers/70627c7476b69114ce0a3b221b16a1575bd9c345671f5052efb8185d42601c3e/start: EOF
vagrant@innoman:/vagrant/notWorking$ docker ps -a
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS              PORTS               NAMES
70627c7476b6        codeship_client         "karma start --single"   43 seconds ago      Created                                 jet-client-clientunittests
d350724be177        codeship_innomanfiles   "true true"              43 seconds ago      Created                                 jet-innomanfiles-clientunittests`

[notWorking.zip](https://files.zenhub.io/56c71c5654b11b79199ff1e7)

If you remove the "volumes_from" in codeship-services.yml the project runs. Or use docker 1.9.1.

**Comment by ireinhart** [comment]
With docker 1.10.2 the problems are solved. I close here.
Thx for your help.

**Comment by mlocher** [comment]
Awesome, great to hear :)
